---
- name: "{{ nginx_setup }} NGINX in Linux systems"
  #when: ansible_facts['system'] | lower is not search('bsd')
  block:
    - name: "{{ nginx_setup | capitalize }} NGINX from repository"
      include_tasks: "install-{{ ansible_facts['os_family'] }}.yml"
      when: nginx_install_from == "nginx_repository"